services:
  - type: web
    name: webapp-alpaca-paper
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: ALPACA_OAUTH_CLIENT_ID
        fromDotEnv: true
      - key: ALPACA_OAUTH_CLIENT_SECRET
        fromDotEnv: true
      - key: ALPACA_OAUTH_REDIRECT_URI
        fromDotEnv: true