services:
  - type: web
    name: webapp-alpaca-paper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn alpaca_controller:app"
    autoDeploy: true