services:
  - type: web
    name: webapp-alpaca-paper
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn alpaca_controller:app"
    envVars:
      - key: ALPACA_API_KEY
        fromEnvVar: ALPACA_API_KEY
      - key: ALPACA_API_SECRET
        fromEnvVar: ALPACA_API_SECRET
